import CryptoKit
import Foundation

// C10: the app side of docs/meet_events_contract.md — wire schema, AEAD
// crypto, signed acks, and the contract dedupe-id formula. Pure types and
// functions; ingestion (DB) lives in MeetEventsIngestor.swift, the
// NWListener HTTP wrapper in BlaiseApp.

// MARK: - Shared secret

/// Lifecycle of the extension shared secret (C12): generated by the app
/// (32 random bytes, hex), stored in the Keychain via the C2 `SecretStore`,
/// shown in Settings with reveal + regenerate, pasted once into the
/// extension's options page.
public enum MeetEventsSecret {
    /// `SecretStore` key (Keychain account name).
    public static let secretStoreKey = "meet.sharedSecret"

    /// 32 random bytes as 64 lowercase hex characters.
    public static func generate() -> String {
        var bytes = [UInt8](repeating: 0, count: 32)
        for index in bytes.indices { bytes[index] = UInt8.random(in: 0...255) }
        return bytes.map { String(format: "%02x", $0) }.joined()
    }
}

// MARK: - Listener bind policy

/// Who may claim 127.0.0.1:18429. FIELD FAILURE (2026-06-11): dev/demo app
/// instances launched with a `BLAISE_DATA_ROOT` override (throwaway data
/// roots in /tmp) held the production port for days; they read the same
/// Keychain secret, so the extension received VALID signed 200s while every
/// captured batch landed in a sqlite file nobody would ever look at — the
/// real database stayed empty across two live meetings. Policy: an instance
/// pointed at an overridden data root never binds the meet-events port
/// unless explicitly opted in (BLAISE_MEET_LISTENER=1, for deliberate
/// integration testing against a scratch root).
public enum MeetEventsListenerPolicy {
    public static func bindAllowed(environment: [String: String]) -> Bool {
        environment["BLAISE_DATA_ROOT"] == nil || environment["BLAISE_MEET_LISTENER"] == "1"
    }

    public static func bindAllowed() -> Bool {
        bindAllowed(environment: ProcessInfo.processInfo.environment)
    }
}

// MARK: - Display-name hygiene (current-Meet scrape fallout)

/// Wire display names from live Meet (June 2026) can carry icon-font
/// ligature text glued to localized control labels — field-captured shape:
/// "keep_outlineFixar Maria Silva na tela principal"
/// (the pin control; the participant name is embedded), "frame_personReenquadrar"
/// (no name at all). The extension ≥ 0.2.0 cleans these at the source, but
/// batches buffered by older extension versions still arrive dirty, so the
/// listener normalizes too (same belt-to-braces stance as the localized-self
/// denylist). Mirrors extension/src/selectors.js `cleanNameCandidate`.
public enum MeetDisplayNameSanitizer {
    /// Pin-control label templates. pt-BR FIELD-VERIFIED 2026-06-11; en
    /// mirrors Google's documented wording (not yet live-verified). Other
    /// locales degrade to the underscore junk gate below.
    static let pinTemplates: [(prefix: String, suffix: String)] = [
        ("Fixar ", " na tela principal"),
        ("Pin ", " to your main screen"),
    ]

    /// A human display name is one short line of text. Field capture
    /// (2026-06-11) showed the pre-0.2.0 scraper also lifting whole CSS/JS
    /// blocks (".ink-canvas-parent { height: 100%; … }") and full UI
    /// sentences ("As pessoas ainda podem ver seu vídeo completo.") into the
    /// name position. None carries an underscore, so the ligature gate let
    /// them through — they reached `meeting_speaker_event` (voting onto a
    /// diarized cluster) and `Meeting.attendees` (rendering verbatim in the
    /// detail header as "json artifacts"). The structural gate below rejects
    /// any candidate that is not name-shaped: contains a markup/structural
    /// metacharacter ({ } < > ; = newline) or runs longer than any real
    /// display name. nil beats wrong, consistent with the ligature rule.
    static let maxNameLength = 80
    static let markupCharacters: Set<Character> = ["{", "}", "<", ">", ";", "=", "\n", "\r", "\t"]

    /// Trim → mine pin templates for the embedded name → reject anything
    /// still carrying an underscore (icon-ligature signature) or a
    /// markup/structural character, or longer than a real display name.
    public static func sanitize(_ raw: String?) -> String? {
        guard let raw else { return nil }
        let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }
        if let pinned = nameFromPinLabel(trimmed) {
            return isNameShaped(pinned) ? pinned : nil
        }
        return isNameShaped(trimmed) ? trimmed : nil
    }

    /// A candidate is name-shaped when it carries no underscore, no markup
    /// metacharacter, and fits within a display-name's length.
    static func isNameShaped(_ candidate: String) -> Bool {
        guard candidate.count <= maxNameLength else { return false }
        guard !candidate.contains("_") else { return false }
        return !candidate.contains { markupCharacters.contains($0) }
    }

    /// "…Fixar <name> na tela principal" → "<name>"; nil when no template
    /// matches. The prefix may be glued to leading ligature text; the suffix
    /// must close the string.
    static func nameFromPinLabel(_ text: String) -> String? {
        for (prefix, suffix) in pinTemplates {
            guard let prefixRange = text.range(of: prefix), text.hasSuffix(suffix) else { continue }
            let start = prefixRange.upperBound
            let end = text.index(text.endIndex, offsetBy: -suffix.count)
            guard start < end else { continue }
            let name = String(text[start..<end]).trimmingCharacters(in: .whitespaces)
            if !name.isEmpty { return name }
        }
        return nil
    }
}

// MARK: - Wire schema (batch plaintext, schemaVersion 1)

public struct MeetWireParticipant: Codable, Sendable, Equatable {
    /// nil BY DESIGN for isSelf entries (the localized self tile label never
    /// travels); also nil when not scrape-able.
    public var displayName: String?
    /// Opaque, per-device/session; may change on rejoin.
    public var participantID: String?
    public var isSelf: Bool

    public init(displayName: String?, participantID: String? = nil, isSelf: Bool) {
        self.displayName = displayName
        self.participantID = participantID
        self.isSelf = isSelf
    }
}

public struct MeetWireEvent: Codable, Sendable, Equatable {
    public var displayName: String?
    public var participantID: String?
    public var isSelf: Bool
    /// Wall-clock epoch millis (closed utterances, coalesced extension-side).
    public var startEpochMillis: Int64
    public var endEpochMillis: Int64

    public init(
        displayName: String?, participantID: String? = nil, isSelf: Bool,
        startEpochMillis: Int64, endEpochMillis: Int64
    ) {
        self.displayName = displayName
        self.participantID = participantID
        self.isSelf = isSelf
        self.startEpochMillis = startEpochMillis
        self.endEpochMillis = endEpochMillis
    }
}

/// Lifecycle control signal riding a v2 batch (C14): never stored as
/// content, never in the per-meeting seen-id set — the tracker's per-code
/// monotonic guard (over `atMs`/`capturedAtMs`) is its replay protection.
public struct MeetWireLifecycle: Codable, Sendable, Equatable {
    public enum Kind: String, Codable, Sendable {
        case callStarted = "call-started"
        case callEnded = "call-ended"
        case heartbeat
    }

    public var kind: Kind
    /// Wall-clock epoch millis of the transition / heartbeat tick.
    public var atMs: Int64
    /// call-ended only: "left" (the 1 s poll lost the in-call UI) or
    /// "pagehide" (tab/window closed, navigation, browser quit).
    public var reason: String?

    public init(kind: Kind, atMs: Int64, reason: String? = nil) {
        self.kind = kind
        self.atMs = atMs
        self.reason = reason
    }
}

public struct MeetWireBatch: Codable, Sendable, Equatable {
    public var meetingCode: String
    public var capturedAtMs: Int64
    public var droppedCount: Int
    public var poisonedCount: Int
    public var roster: [MeetWireParticipant]
    public var events: [MeetWireEvent]
    public var schemaVersion: Int
    /// OPTIONAL (schema v2, C14): a v1 batch is a v2 batch with no lifecycle.
    public var lifecycle: MeetWireLifecycle? = nil

    /// Content-free liveness ping (C14): volatile on the extension side and
    /// never stored pending when unmatched.
    public var isHeartbeatOnly: Bool {
        lifecycle?.kind == .heartbeat && events.isEmpty && roster.isEmpty
    }
}

/// `POST /v1/meet-events` request body — `{iv, ciphertext}` (base64),
/// nothing else.
public struct MeetWireEnvelope: Codable, Sendable, Equatable {
    public var iv: String
    public var ciphertext: String

    public init(iv: String, ciphertext: String) {
        self.iv = iv
        self.ciphertext = ciphertext
    }
}

// MARK: - Crypto (pinned parameters)

public enum MeetEventsCryptoError: Error, Equatable {
    case malformedEnvelope
    case decryptFailed
}

public enum MeetEventsCrypto {
    /// AAD, pinned.
    public static let aad = "blaise-meet-events-v1"
    /// Signed-ack response header.
    public static let ackHeader = "X-Blaise-Ack"

    static let ackPrefix = "ack-v1:"
    static let gcmTagBytes = 16

    /// AES key = SHA-256(utf8(secret)).
    static func aesKey(secret: String) -> SymmetricKey {
        SymmetricKey(data: SHA256.hash(data: Data(secret.utf8)))
    }

    /// Ack key = SHA-256(utf8(secret) ‖ utf8("ack")) — domain-separated.
    static func ackKey(secret: String) -> SymmetricKey {
        SymmetricKey(data: SHA256.hash(data: Data((secret + "ack").utf8)))
    }

    /// Decrypts an envelope (AES-256-GCM, WebCrypto layout: GCM tag appended
    /// to the ciphertext). Throws `.malformedEnvelope` when the base64/IV
    /// shape is wrong, `.decryptFailed` on authentication failure.
    public static func decrypt(_ envelope: MeetWireEnvelope, secret: String) throws -> Data {
        guard
            let iv = Data(base64Encoded: envelope.iv), iv.count == 12,
            let combined = Data(base64Encoded: envelope.ciphertext), combined.count > gcmTagBytes
        else {
            throw MeetEventsCryptoError.malformedEnvelope
        }
        let ciphertext = combined.prefix(combined.count - gcmTagBytes)
        let tag = combined.suffix(gcmTagBytes)
        do {
            let box = try AES.GCM.SealedBox(
                nonce: AES.GCM.Nonce(data: iv), ciphertext: ciphertext, tag: tag)
            return try AES.GCM.open(box, using: aesKey(secret: secret), authenticating: Data(aad.utf8))
        } catch {
            throw MeetEventsCryptoError.decryptFailed
        }
    }

    /// `base64(HMAC-SHA256(ackKey, "ack-v1:" + base64(IV) + ":" + status))` —
    /// status-bound, message-bound. `ivBase64` is the EXACT `iv` string from
    /// the request body.
    public static func ackSignature(secret: String, ivBase64: String, status: Int) -> String {
        let message = ackPrefix + ivBase64 + ":" + String(status)
        let mac = HMAC<SHA256>.authenticationCode(
            for: Data(message.utf8), using: ackKey(secret: secret))
        return Data(mac).base64EncodedString()
    }
}

// MARK: - Dedupe id (contract formula, PRE-substitution wire fields)

extension MeetWireEvent {
    /// `meetingCode:participantID-or-displayName-or-"self":startMs:endMs` —
    /// byte-equal to the extension's `dedupeID()` (events.js), computed from
    /// the RAW wire fields before any denylist/identity transform so identity
    /// renames can never break replay protection.
    public func dedupeID(meetingCode: String) -> String {
        let key = participantID ?? displayName ?? (isSelf ? "self" : "")
        return "\(meetingCode):\(key):\(startEpochMillis):\(endEpochMillis)"
    }
}
