import Foundation
import Testing
@testable import BlaiseCore

// Fully-synthetic PT/EN code-switching BYTE-PIN — the deterministic bilingual
// CI guard. The shipped ICSI audio fixture is English-only and the
// opportunistic-local PT/EN test skips in CI, so without this suite CI carries
// NO Portuguese/English code-switching regression guard.
//
// Inputs are HAND-AUTHORED (no audio, no models): a RawASREnvelope and a
// DiarizationOutput in the Vexatron Labs / Quoll Harbour universe that mix
// Portuguese and English within one meeting (PT-dominant), with misheard vocab
// aliases the corrector must repair to canonical forms. The pin is generated by
// running the in-process, deterministic Tier1Chain over those inputs — same
// chain the ICSI Tier-1 pin uses — so it needs no weights and runs in CI.
//
// Regenerate the pin deliberately with BLAISE_MINT_CODESWITCH=1 (see
// mintCodeswitchPin below); the always-on test never writes.

enum SyntheticCodeswitch {
    static var directory: URL {
        VocabFixtures.repoRoot.appendingPathComponent(
            "fixtures/synthetic_codeswitch", isDirectory: true)
    }
    static var rawASRURL: URL { directory.appendingPathComponent("raw_asr.json") }
    static var diarizationURL: URL { directory.appendingPathComponent("diarization.json") }
    static var intermediateURL: URL {
        directory.appendingPathComponent("transcript_intermediate_pinned.json")
    }

    /// The hand-authored inputs' max segment end time (50.9 s) — the
    /// audioDuration the normalizer clamps against. No real audio exists; this
    /// constant IS the duration the fixture is authored to.
    static let audioDuration = 50.9

    /// The dominant language the inputs are designed to exercise (more PT
    /// function-word segments than EN, on genuine code-switched content).
    static let expectedDominantLanguage = "pt"

    /// Canonical forms the corrector must produce where the misheard aliases
    /// ("Nira", "Zandi", "Tobes") appear in the raw input.
    static let expectedCanonicals = ["Elena Marquez", "Luca Zander", "Toban Vane"]
    static let mishearAliases = ["Nira", "Zandi", "Tobes"]

    static func loadInputs() throws -> (RawASREnvelope, DiarizationOutput) {
        let envelope = try RawASREnvelope.load(from: rawASRURL)
        let diarization = try JSONDecoder().decode(
            DiarizationOutput.self, from: Data(contentsOf: diarizationURL))
        return (envelope, diarization)
    }
}

@Suite struct SyntheticCodeswitchPinTests {
    /// Always-on, no env gate, no models: load the committed bilingual inputs,
    /// run the deterministic Tier-1 chain TWICE, and assert the output is
    /// byte-identical to the committed pin AND stable across runs. Also assert
    /// the designed PT dominance and that the vocab correction fired (canonical
    /// names replace the misheard aliases).
    @Test func tier1ByteStableBilingualPin() throws {
        let (envelope, diarization) = try SyntheticCodeswitch.loadInputs()
        let vocabulary = try VocabFixtures.pipelineVocabulary()
        let pinnedBytes = try Data(contentsOf: SyntheticCodeswitch.intermediateURL)

        var previous: Data?
        var corrected: [TranscriptSegment] = []
        var dominant = ""
        for runIndex in 1 ... 2 {
            let (segments, dominantLanguage) = Tier1Chain.run(
                envelope: envelope,
                diarization: diarization,
                audioDuration: SyntheticCodeswitch.audioDuration,
                vocabulary: vocabulary)
            let bytes = try pinBytes(segments.map(PinnedSegment.init))
            #expect(
                bytes == pinnedBytes,
                "run \(runIndex): synthetic code-switch Tier-1 output diverged from the committed pin — a deterministic stage changed; fix it or re-mint deliberately with BLAISE_MINT_CODESWITCH=1")
            if let previous {
                #expect(bytes == previous, "Tier-1 chain not byte-stable across in-process runs")
            }
            previous = bytes
            corrected = segments
            dominant = dominantLanguage
        }

        // Designed PT dominance on code-switched input.
        #expect(
            dominant == SyntheticCodeswitch.expectedDominantLanguage,
            "expected PT-dominant classification, got \(dominant)")

        // The vocab correction FIRED: each canonical appears in the corrected
        // output, and none of the misheard aliases survive as standalone words.
        let correctedText = corrected.map(\.text).joined(separator: " ")
        for canonical in SyntheticCodeswitch.expectedCanonicals {
            #expect(
                correctedText.contains(canonical),
                "canonical '\(canonical)' missing — vocab correction did not fire on the code-switched input")
        }
        let correctedTokens = WordSimilarity.tokens(correctedText)
        for alias in SyntheticCodeswitch.mishearAliases {
            #expect(
                !correctedTokens.contains(alias.lowercased()),
                "misheard alias '\(alias)' survived correction")
        }
    }

    /// Gated regeneration (BLAISE_MINT_CODESWITCH=1): rewrites the committed
    /// pin from the hand-authored inputs. A small, committed reproducer for the
    /// pin — mirrors the project's mint approach so pin generation is code, not
    /// prose. Never runs in CI or a normal local run.
    @Test func mintCodeswitchPin() throws {
        guard ProcessInfo.processInfo.environment["BLAISE_MINT_CODESWITCH"] == "1" else { return }
        let (envelope, diarization) = try SyntheticCodeswitch.loadInputs()
        let vocabulary = try VocabFixtures.pipelineVocabulary()
        let (segments, _) = Tier1Chain.run(
            envelope: envelope,
            diarization: diarization,
            audioDuration: SyntheticCodeswitch.audioDuration,
            vocabulary: vocabulary)
        try pinBytes(segments.map(PinnedSegment.init))
            .write(to: SyntheticCodeswitch.intermediateURL)
        print("[mint-codeswitch] wrote \(segments.count) segments to \(SyntheticCodeswitch.intermediateURL.path)")
    }
}
