#!/bin/bash
# Generates app/Sources/BlaiseCore/Resources/python_requirements.txt (the
# SHARED whisper + notes pin set; renamed from whisper_requirements.txt by
# C6) from the HAND-AUTHORED pin list below with per-file sha256 hashes
# fetched from PyPI's JSON API. We deliberately do NOT use `uv pip compile`:
# it would resolve mlx-whisper's declared-but-unused torch dependency into the
# lockfile (388 MB the research basis excludes); installs run
# `--no-deps --require-hashes` against this exact set instead.
#
# C6 additions: mlx-lm==0.31.3 + outlines==1.3.0 and their import closure,
# hand-enumerated from a uv resolution probed on 2026-06-10 and then TRIMMED:
# outlines' declared-but-unimported heavy family (datasets, pandas, pyarrow,
# multiprocess, dill, xxhash, aiohttp + aiohappyeyeballs/aiosignal/frozenlist/
# multidict/propcache/yarl) is excluded — verified by importing outlines,
# every outlines.backends/processors/models submodule, and mlx_lm.{utils,
# generate,sample_utils} in a venv without them. The torch-absent assertion
# below still runs.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/app/Sources/BlaiseCore/Resources/python_requirements.txt"

# Hand-authored pins (research/c3_asr_engines.md §2; Python 3.12).
PINS=(
    "mlx-whisper==0.4.3"
    "mlx==0.31.2"
    "mlx-metal==0.31.2"
    "numpy==2.4.6"
    "numba==0.65.1"
    "llvmlite==0.47.0"
    "scipy==1.17.1"
    "tiktoken==0.13.0"
    "tqdm==4.68.2"
    "more-itertools==11.1.0"
    "huggingface_hub==1.18.0"
    # huggingface_hub 1.x imports httpx (not requests) at snapshot_download
    # time — caught by the AC3 import check on 2026-06-10; versions taken
    # from the working research venv. sniffio/anyio are deliberately absent:
    # the research venv has no sniffio (anyio cannot import without it),
    # which proves the sync hub/httpx path never imports anyio.
    "httpx==0.28.1"
    "httpcore==1.0.9"
    "h11==0.16.0"
    "hf-xet==1.5.1"
    "filelock==3.29.1"
    "fsspec==2026.4.0"
    "packaging==26.2"
    "requests==2.34.2"
    "charset-normalizer==3.4.7"
    "idna==3.18"
    "urllib3==2.7.0"
    "certifi==2026.5.20"
    "regex==2026.5.9"
    "PyYAML==6.0.3"
    "typing_extensions==4.15.0"
    # --- C6 notes-synthesis stack (mlx-lm + outlines; see header) ---
    "mlx-lm==0.31.3"
    "outlines==1.3.0"
    "outlines-core==0.2.14"
    "transformers==5.10.2"
    "tokenizers==0.22.2"
    "safetensors==0.8.0"
    "sentencepiece==0.2.1"
    "protobuf==7.35.0"
    "jinja2==3.1.6"
    "markupsafe==3.0.3"
    "pydantic==2.13.4"
    "pydantic-core==2.46.4"
    "annotated-types==0.7.0"
    "annotated-doc==0.0.4"
    "typing-inspection==0.4.2"
    "jsonschema==4.26.0"
    "jsonschema-specifications==2025.9.1"
    "referencing==0.37.0"
    "rpds-py==2026.5.1"
    "attrs==26.1.0"
    "genson==1.3.0"
    "jsonpath-ng==1.8.0"
    "diskcache==5.6.3"
    "cloudpickle==3.1.2"
    "pillow==12.2.0"
    "anyio==4.13.0"
    "click==8.4.1"
    "rich==15.0.0"
    "markdown-it-py==4.2.0"
    "mdurl==0.1.2"
    "pygments==2.20.0"
    "typer==0.25.1"
    "shellingham==1.5.4"
    "python-dateutil==2.9.0.post0"
    "six==1.17.0"
)

# Torch must never enter this set (the whole point of hand-authoring).
for pin in "${PINS[@]}"; do
    name="${pin%%==*}"
    lowered="$(printf '%s' "$name" | tr '[:upper:]_' '[:lower:]-')"
    if [[ "$lowered" == "torch" || "$lowered" == torch-* ]]; then
        echo "ERROR: torch found in pin list ($pin) — refusing to generate" >&2
        exit 1
    fi
done

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
    echo "# GENERATED by scripts/fetch_pypi_hashes.sh — do not edit hashes by hand."
    echo "# Shared whisper (research/c3_asr_engines.md §2) + notes (C6: mlx-lm/outlines)"
    echo "# pin set; torch and outlines' unimported heavy deps excluded (see script)."
    echo "# Installed with: uv pip install --no-deps --require-hashes -r <this file>"
} > "$TMP"

for pin in "${PINS[@]}"; do
    name="${pin%%==*}"
    version="${pin##*==}"
    echo "Fetching hashes: $name==$version" >&2
    json="$(curl -fsSL "https://pypi.org/pypi/$name/$version/json")"
    hashes="$(printf '%s' "$json" | python3 -c '
import json, sys
data = json.load(sys.stdin)
digests = [f["digests"]["sha256"] for f in data["urls"]]
if not digests:
    raise SystemExit("no release files on PyPI")
for d in digests:
    print(d)
')"
    {
        printf '%s' "$pin"
        while IFS= read -r h; do
            printf ' \\\n    --hash=sha256:%s' "$h"
        done <<< "$hashes"
        printf '\n'
    } >> "$TMP"
done

# Belt-and-braces: assert torch absent from the generated file.
if grep -qiE '^torch([=<>!~ ]|$)' "$TMP"; then
    echo "ERROR: torch present in generated requirements — aborting" >&2
    exit 1
fi

mv "$TMP" "$OUT"
trap - EXIT
echo "Wrote $OUT"
